### ISSUE TITLE
Jade version outdated

### ISSUE THREAD

**Issue by LinusU** [naltatis/jade-syntax-docs#10]
The version of Jade is quite outdated, one major change that I recently ripped my hair out for is the transition from `div(attributes)` to `div(&attributes=attributes)`. The former which works on your website, and the latter which worked in recent versions of Jade.

**Comment by naltatis** [comment]
Jade version is new current. I've also corrected the attributes example. Thanks for the issue!

**Comment by LinusU** [comment]
Wow, nice to see this in the inbox, thanks!
