### ISSUE TITLE
Do not allow tab key in "html output" textarea

### ISSUE THREAD

**Issue by wjbryant** [naltatis/jade-syntax-docs#5]
Pressing the tab key in the "html output" textarea inserts spaces into the markup, even though input is supposed to be disabled. Instead of applying Tab Override to all textarea elements, it should be limited to the textareas that accept input:

``` javascript
$('textarea.jade,textarea.json').tabOverride();
```

**Comment by naltatis** [comment]
HTML now isn't tabbable any more. Thanks!
